### ISSUE TITLE
Quasiquotes fail to parse in GHC 8.8.3

### ISSUE THREAD

**Issue by masaeedu** [tfausak/splint#9] opened 2021-03-29 19:20 UTC
I have the following code in `Test.hs`:

```
module Test where

import Text.Regex.PCRE.Heavy (Regex, re)

foo :: String
foo = concat $ map show [1, 2, 3 :: Integer]

numRegex :: Regex
numRegex = [re|^[0-9]{9}$|]
```

Now I want to lint this file while I compile it. IIUC the following command line incantation should do that:

```
ghc -XQuasiQuotes -fplugin=Splint -fforce-recomp Test.hs
```

I also make sure to put the following in my `.hlint.yaml`:

```
➜  mwb-error-bash git:(mwb-error-bash) ✗ cat .hlint.yaml
- arguments: [-XQuasiQuotes]
```

However, when I run the command shown above, I get:

```
➜  mwb-error-bash git:(mwb-error-bash) ✗ ghc -XQuasiQuotes -fplugin=Splint -fforce-recomp Test.hs
[1 of 1] Compiling Test             ( Test.hs, Test.o )
ghc: panic! (the 'impossible' happened)
  (GHC version 8.8.3 for x86_64-unknown-linux):
        ParseError { parseErrorLocation = RealSrcSpan SrcSpanOneLine "Test.hs" 9 23 24, parseErrorMessage = "parse error on input `9'", parseErrorContents = "  numRegex :: Regex\n> numRegex = [re|^[0-9]{9}$|]\n" }

Please report this as a GHC bug:  https://www.haskell.org/ghc/reportabug
```

But GHC itself seems to be perfectly happy with the file. If I remove `-fplugin=Splint`, I get:

```
➜  mwb-error-bash git:(mwb-error-bash) ✗ ghc -XQuasiQuotes -fforce-recomp Test.hs
[1 of 1] Compiling Test             ( Test.hs, Test.o )
```

Invoking HLint from the command line seems to work as well:

```
➜  mwb-error-bash git:(mwb-error-bash) ✗ hlint --version
HLint v3.1.6, (C) Neil Mitchell 2006-2020
➜  mwb-error-bash git:(mwb-error-bash) ✗ hlint Test.hs
Test.hs:6:7-44: Warning: Use concatMap
Found:
  concat $ map show [1, 2, 3 :: Integer]
Perhaps:
  concatMap show [1, 2, 3 :: Integer]

1 hint
```

Just to confirm my suspicions, I tried compiling the file without the plugin, but also without the `QuasiQuotes` extension enabled. This results in a parse error in the same location observed in the GHC panic earlier:

```
➜  mwb-error-bash git:(mwb-error-bash) ✗ ghc -fforce-recomp Test.hs
[1 of 1] Compiling Test             ( Test.hs, Test.o )

Test.hs:9:23: error: parse error on input ‘9’
  |
9 | numRegex = [re|^[0-9]{9}$|]
  |                       ^
```

So AFAICT what's going wrong is that the .hlint.yaml file is not being respected when reparsing the file (i.e. it's not accounting for the additional grammar introduced by -XQuasiQuotes when reparsing).

Versions of things:

ghc: 8.8.3
hlint: 3.1.6
splint: 1.0.1.1

The problem also occurs with splint 1.0.1.2.

**Comment by tfausak** [comment] 2021-03-30 12:04
Thanks for reporting this! 

I was able to reproduce this problem. I made a slightly smaller example that uses `raw-strings-qq`, which is hopefully easier to build:

``` hs
import Text.RawString.QQ -- raw-strings-qq
main = print [r||]
```

I'm on commit f06756e738813f9a8112237a217f57d5bc588eaa with GHC 8.8.4 and Stack 2.5.1. I have the same HLint configuration as you. This is the behavior I see:

``` sh
» stack exec --package raw-strings-qq -- \
  ghc -fforce-recomp -XQuasiQuotes -fplugin=Splint gh9/Main.hs
[1 of 1] Compiling Main             ( gh9/Main.hs, gh9/Main.o )
ghc: panic! (the 'impossible' happened)
  (GHC version 8.8.4 for x86_64-unknown-linux):
	ParseError { parseErrorLocation = RealSrcSpan SrcSpanOneLine "gh9/Main.hs" 2 16 19, parseErrorMessage = "parse error on input `||]'", parseErrorContents = "  import Text.RawString.QQ -- raw-strings-qq\n> main = print [r||]\n" }

Please report this as a GHC bug:  https://www.haskell.org/ghc/reportabug
```

Explicitly passing `-XQuasiQuotes` to Splint via `-fplugin-opt` works:

``` sh
» stack exec --package raw-strings-qq -- \
  ghc -fforce-recomp -XQuasiQuotes -fplugin=Splint -fplugin-opt=Splint:-XQuasiQuotes gh9/Main.hs
[1 of 1] Compiling Main             ( gh9/Main.hs, gh9/Main.o )
Linking gh9/Main ...
```

Explicitly pointing to the configuration file doesn't fix things:

``` sh
» stack exec --package raw-strings-qq -- \
  ghc -fforce-recomp -XQuasiQuotes -fplugin=Splint -fplugin-opt=Splint:--hint=.hlint.yaml gh9/Main.hs
[1 of 1] Compiling Main             ( gh9/Main.hs, gh9/Main.o )
ghc: panic! (the 'impossible' happened)
  (GHC version 8.8.4 for x86_64-unknown-linux):
	ParseError { parseErrorLocation = RealSrcSpan SrcSpanOneLine "gh9/Main.hs" 2 16 19, parseErrorMessage = "parse error on input `||]'", parseErrorContents = "  import Text.RawString.QQ -- raw-strings-qq\n> main = print [r||]\n" }

Please report this as a GHC bug:  https://www.haskell.org/ghc/reportabug
```

But pointing to a configuration file that doesn't exist causes a different (expected) problem:

``` sh
» stack exec --package raw-strings-qq -- \
  ghc -fforce-recomp -XQuasiQuotes -fplugin=Splint -fplugin-opt=Splint:--hint=does-not-exist gh9/Main.hs
[1 of 1] Compiling Main             ( gh9/Main.hs, gh9/Main.o )
user error (Failed to find requested hint files:
  does-not-exist
)
```

So the arguments are being passed through correctly and the configuration file is being read correctly. Perhaps I misunderstood how HLint's configuration is loaded? It seems like the command-line arguments are clobbering the arguments in the configuration file. That's especially strange since, as you noted, HLint itself works fine:

``` sh
» hlint --hint .hlint.yaml gh9/Main.hs
No hints
```

You can see how HLint handles this in the [`readAllSettings`](https://hackage.haskell.org/package/hlint-3.3/docs/src/HLint.html#readAllSettings) function. Unfortunately that function isn't exported, so Splint uses [`argsSettings`](https://hackage.haskell.org/package/hlint-3.3/docs/Language-Haskell-HLint.html#v:argsSettings) instead. 

I think the fix will be to read the settings file and merge its arguments with the command-line arguments, but I don't know how to do that just yet.

**Comment by masaeedu** [comment] 2021-03-31 00:36
Nice, glad you were able to reproduce. I was actually trying the explicit file thing but was doing something stupid and only passing `-fplugin-opt`, didn't realize you also have to pass `-fplugin` :facepalm: .

**Comment by tfausak** [comment] 2021-04-01 23:11
I thought I could be clever and use `argsSettings` if the list of command line arguments was empty, but it turns out that doesn't work either. At this point I think it's reasonable to call this a bug in HLint and ask for help upstream. I'll open an issue against HLint. 

In the meantime, as a workaround you can pass `-fplugin-opt=Splint:...` to set whichever options you're already setting in `.hlint.yaml`. Clearly that's not ideal, but I think it's the only workaround here.

**Comment by masaeedu** [comment] 2021-04-09 19:32
@tfausak Does this bug affect usage of splint on GHC 8.10+ as well?

**Comment by tfausak** [comment] 2021-04-10 12:41
GHC 8.10+ won't have this particular problem with the language extensions, but it may have other problems related to https://github.com/ndmitchell/hlint/issues/1232.

**Comment by tfausak** [comment] 2021-11-29 15:22
I'm going to close this. It's an upstream issue. I'm not sure how Splint could work around it. Also it shouldn't happen with GHC 8.10+.

**Closed by tfausak** 2021-11-29 15:22 UTC
